imports:
    - { resource: parameters.dist.yml }
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    secret: %secret%
    default_locale: ru
    router: { resource: "%kernel.root_dir%/config/routing.yml" }
    templating: { engines: [twig] }
    form: ~
    csrf_protection: ~
    session: ~
    translator: ~
    validation: { enable_annotations: true }

twig:
    globals:
        vk_api_id: %vk_api_id%

doctrine:
    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType
        driver: %database_driver%
        host: %database_host%
        port: %database_port%
        dbname: %database_name%
        user: %database_user%
        password: %database_password%
        path: %database_path%
        charset: UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        auto_mapping: true

assetic:
    filters:
        compass: ~

stof_doctrine_extensions:
    default_locale: ru_RU
    orm:
        default:
            timestampable: true
            sluggable: true

stfalcon_tinymce:
    textarea_class: tinymce
    theme:
        simple:
            theme: advanced
            plugins: table,paste,contextmenu
            theme_advanced_buttons1: bold,italic,underline,|,justifyleft,justifycenter,justifyright,|,sub,sup,|,cut,copy,paste,pastetext,pasteword
            theme_advanced_buttons2: undo,redo,|,bullist,numlist,|,link,unlink,image
            theme_advanced_buttons3: tablecontrols
            theme_advanced_statusbar_location: none

foq_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        website:
            client: default
            types:
                page:
                    mappings:
                        title: { boost: 5 }
                        content: { boost: 3 }
                    persistence:
                        driver: orm
                        model: Rithis\BECRussiaBundle\Entity\Page
                        provider:
                            query_builder_method: createIsRealQueryBuilder
                        listener: ~
                        finder: ~

sonata_media:
    default_context: news
    db_driver: doctrine_orm
    contexts:
        news:
            providers:
                - sonata.media.provider.image
            formats:
                small: { width: 80, height: 80, quality: 70 }
                medium: { width: 160, height: 160, quality: 70 }
                big: { width: 220, height: 220, quality: 70 }
        school:
            providers:
                - sonata.media.provider.image
            formats:
                small: { width: 80, height: 80, quality: 70 }
                medium: { width: 160, height: 160, quality: 70 }
                big: { width: 220, height: 220, quality: 70 }
        school_gallery:
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.youtube
            formats:
                small: { width: 80, height: 80, quality: 70 }
                medium: { width: 160, height: 160, quality: 70 }
                big: { width: 220, height: 220, quality: 70 }
        teacher:
            providers:
                - sonata.media.provider.image
            formats:
                medium: { width: 160, height: 160, quality: 70 }
        education_course:
            providers:
                - sonata.media.provider.image
            formats:
                medium: { width: 160, height: 160, quality: 70 }
                big: { width: 220, height: 220, quality: 70 }
        ed_course_type:
            providers:
                - sonata.media.provider.image
            formats:
                big: { width: 800, height: 400, quality: 70 }
        library:
            download:
                strategy: sonata.media.security.public_strategy
                mode: http
            providers:
                - rithis.becrussia.library.provider.article
                - rithis.becrussia.library.provider.book
                - rithis.becrussia.library.provider.video
                - rithis.becrussia.library.provider.audio
                - rithis.becrussia.library.provider.soft
            formats:
                default: {}
    cdn:
        server:
            path: /uploads/media
    filesystem:
        local:
            directory: %kernel.root_dir%/../web/uploads/media
            create: true
    class:
        media: Rithis\BECRussiaBundle\Entity\Media
        gallery: Rithis\BECRussiaBundle\Entity\Gallery
        gallery_has_media: Rithis\BECRussiaBundle\Entity\GalleryHasMedia

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_admin:
    dashboard:
        groups:
            Towns: { items: [rithis.becrussia.admin.town] }
            Courses: { items: [rithis.becrussia.admin.education_course] }
            Schools: { items: [rithis.becrussia.admin.school, rithis.becrussia.admin.teacher] }
            News: { items: [rithis.becrussia.admin.news] }
            Vacancies: { items: [rithis.becrussia.admin.vacancy] }
            Poll: { items: [rithis.becrussia.admin.poll] }
            Test: { items: [rithis.becrussia.admin.test_question, rithis.becrussia.admin.test_result] }
            Page: { items: [rithis.becrussia.admin.page] }
            Library: { items: [rithis.becrussia.admin.library] }
    templates:
        layout: ::admin_layout.html.twig
