imports:
    - { resource: parameters.dist.yml }
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    secret: %secret%
    router: { resource: "%kernel.root_dir%/config/routing.yml" }
    templating: { engines: [twig] }
    form: ~
    csrf_protection: ~
    session: ~
    translator: ~

doctrine:
    dbal:
        driver: %database_driver%
        host: %database_host%
        port: %database_port%
        dbname: %database_name%
        user: %database_user%
        password: %database_password%
        path: %database_path%
        charset: UTF8
    orm:
        auto_mapping: true

assetic:
    filters:
        compass: ~

stof_doctrine_extensions:
    default_locale: ru_RU
    orm:
        default:
            timestampable: true
            sluggable: true

stfalcon_tinymce:
    textarea_class: tinymce
    theme:
        simple:
            theme: advanced
            plugins: table,paste,contextmenu
            theme_advanced_buttons1: bold,italic,underline,|,justifyleft,justifycenter,justifyright,|,sub,sup,|,cut,copy,paste,pastetext,pasteword
            theme_advanced_buttons2: undo,redo,|,bullist,numlist,|,link,unlink,image
            theme_advanced_buttons3: tablecontrols
            theme_advanced_statusbar_location: none

sonata_media:
    default_context: news
    db_driver: doctrine_orm
    contexts:
        news:
            providers:
                - sonata.media.provider.image
            formats:
                small: { width: 80, height: 80, quality: 70 }
                medium: { width: 160, height: 160, quality: 70 }
                big: { width: 220, height: 220, quality: 70 }
        school:
            providers:
                - sonata.media.provider.image
            formats:
                small: { width: 80, height: 80, quality: 70 }
                medium: { width: 160, height: 160, quality: 70 }
                big: { width: 220, height: 220, quality: 70 }
        teacher:
            providers:
                - sonata.media.provider.image
            formats:
                medium: { width: 80, height: 80, quality: 70 }
        education_course:
            providers:
                - sonata.media.provider.image
            formats:
                big: { width: 800, height: 400, quality: 70 }
    cdn:
        server:
            path: /uploads/media
    filesystem:
        local:
            directory: %kernel.root_dir%/../web/uploads/media
            create: true
    class:
        media: Rithis\BECRussiaBundle\Entity\Media
        gallery: Rithis\BECRussiaBundle\Entity\Gallery
        gallery_has_media: Rithis\BECRussiaBundle\Entity\GalleryHasMedia

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_admin:
    dashboard:
        groups:
            Towns: { items: [rithis.becrussia.admin.town] }
            Courses: { items: [rithis.becrussia.admin.education_course] }
            Schools: { items: [rithis.becrussia.admin.school, rithis.becrussia.admin.teacher] }
            News: { items: [rithis.becrussia.admin.news] }
            Vacancies: { items: [rithis.becrussia.admin.vacancy] }
    templates:
        layout: ::admin_layout.html.twig
