<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121204202519 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE books DROP CONSTRAINT fk_4a1b2a9212469de2");
        $this->addSql("DROP SEQUENCE books_id_seq");
        $this->addSql("DROP SEQUENCE book_categories_id_seq");
        $this->addSql("DROP TABLE school_galleries");
        $this->addSql("DROP TABLE book_categories");
        $this->addSql("DROP TABLE books");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("CREATE SEQUENCE books_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE book_categories_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE TABLE school_galleries (id INT NOT NULL, school_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, context VARCHAR(255) NOT NULL, default_format VARCHAR(255) NOT NULL, enabled BOOLEAN NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, slug VARCHAR(140) NOT NULL, provider VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX idx_8641ad0ac32a47ee ON school_galleries (school_id)");
        $this->addSql("CREATE TABLE book_categories (id INT NOT NULL, slug VARCHAR(140) NOT NULL, name VARCHAR(140) NOT NULL, description TEXT NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE TABLE books (id INT NOT NULL, category_id INT DEFAULT NULL, file_id INT DEFAULT NULL, slug VARCHAR(140) NOT NULL, name VARCHAR(140) NOT NULL, description TEXT NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX idx_4a1b2a9212469de2 ON books (category_id)");
        $this->addSql("CREATE UNIQUE INDEX uniq_4a1b2a9293cb796c ON books (file_id)");
        $this->addSql("ALTER TABLE books ADD CONSTRAINT fk_4a1b2a9212469de2 FOREIGN KEY (category_id) REFERENCES book_categories (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
    }
}
