services:
   rithis.becrussia.admin.town:
      class: Rithis\BECRussiaBundle\Admin\TownAdmin
      arguments: [null, Rithis\BECRussiaBundle\Entity\Town, SonataAdminBundle:CRUD]
      tags:
        - { name: sonata.admin, manager_type: orm, group: Towns, label: Town }

   rithis.becrussia.admin.education_course_type:
      class: Rithis\BECRussiaBundle\Admin\EducationCourseTypeAdmin
      arguments: [null, Rithis\BECRussiaBundle\Entity\EducationCourseType, SonataAdminBundle:CRUD]
      tags:
        - { name: sonata.admin, manager_type: orm, group: Courses, label: Education Course Type }

   rithis.becrussia.admin.education_course:
      class: Rithis\BECRussiaBundle\Admin\EducationCourseAdmin
      arguments: [null, Rithis\BECRussiaBundle\Entity\EducationCourse, SonataAdminBundle:CRUD]
      tags:
        - { name: sonata.admin, manager_type: orm, group: Courses, label: Education Course }

   rithis.becrussia.admin.school:
      class: Rithis\BECRussiaBundle\Admin\SchoolAdmin
      arguments: [null, Rithis\BECRussiaBundle\Entity\School, SonataAdminBundle:CRUD]
      tags:
        - { name: sonata.admin, manager_type: orm, group: Schools, label: School }
      calls:
          - [ addChild, [ @rithis.becrussia.admin.school_gallery ] ]

   rithis.becrussia.admin.school_comment:
      class: Rithis\BECRussiaBundle\Admin\SchoolCommentAdmin
      arguments: [null, Rithis\BECRussiaBundle\Entity\SchoolComment, SonataAdminBundle:CRUD]
      tags:
        - { name: sonata.admin, manager_type: orm, group: Schools, label: Comment }

   rithis.becrussia.admin.school_gallery:
      class: Rithis\BECRussiaBundle\Admin\SchoolGalleryAdmin
      arguments: [null, Rithis\BECRussiaBundle\Entity\Gallery, RithisBECRussiaBundle:SchoolGalleryAdmin, @sonata.media.pool, @translator]
      tags:
        - { name: sonata.admin, manager_type: orm, group: Schools, label: Gallery }

   rithis.becrussia.admin.phone:
      class: Rithis\BECRussiaBundle\Admin\PhoneAdmin
      arguments: [null, Rithis\BECRussiaBundle\Entity\Phone, SonataAdminBundle:CRUD]
      tags:
        - { name: sonata.admin, manager_type: orm, group: Schools, label: Phone }

   rithis.becrussia.admin.teacher:
      class: Rithis\BECRussiaBundle\Admin\TeacherAdmin
      arguments: [null, Rithis\BECRussiaBundle\Entity\Teacher, SonataAdminBundle:CRUD]
      tags:
        - { name: sonata.admin, manager_type: orm, group: Schools, label: Teacher }

   rithis.becrussia.admin.news:
      class: Rithis\BECRussiaBundle\Admin\NewsAdmin
      arguments: [null, Rithis\BECRussiaBundle\Entity\News, SonataAdminBundle:CRUD]
      tags:
        - { name: sonata.admin, manager_type: orm, group: News, label: News }

   rithis.becrussia.admin.vacancy:
      class: Rithis\BECRussiaBundle\Admin\VacancyAdmin
      arguments: [null, Rithis\BECRussiaBundle\Entity\Vacancy, SonataAdminBundle:CRUD]
      tags:
        - { name: sonata.admin, manager_type: orm, group: Vacancies, label: Vacancy }

   rithis.becrussia.admin.poll:
      class: Rithis\BECRussiaBundle\Admin\PollAdmin
      arguments: [null, Rithis\BECRussiaBundle\Entity\Poll, SonataAdminBundle:CRUD]
      tags:
        - { name: sonata.admin, manager_type: orm, group: Poll, label: Poll }

   rithis.becrussia.admin.poll_answer:
      class: Rithis\BECRussiaBundle\Admin\PollAnswerAdmin
      arguments: [null, Rithis\BECRussiaBundle\Entity\PollAnswer, SonataAdminBundle:CRUD]
      tags:
        - { name: sonata.admin, manager_type: orm, group: Poll, label: Poll Answer }

   rithis.becrussia.admin.test_answer:
      class: Rithis\BECRussiaBundle\Admin\TestAnswerAdmin
      arguments: [null, Rithis\BECRussiaBundle\Entity\TestAnswer, SonataAdminBundle:CRUD]
      tags:
        - { name: sonata.admin, manager_type: orm, group: Test, label: Test Answer }

   rithis.becrussia.admin.test_question:
      class: Rithis\BECRussiaBundle\Admin\TestQuestionAdmin
      arguments: [null, Rithis\BECRussiaBundle\Entity\TestQuestion, SonataAdminBundle:CRUD]
      tags:
        - { name: sonata.admin, manager_type: orm, group: Test, label: Test Question }

   rithis.becrussia.admin.test_result:
      class: Rithis\BECRussiaBundle\Admin\TestResultAdmin
      arguments: [null, Rithis\BECRussiaBundle\Entity\TestResult, SonataAdminBundle:CRUD]
      tags:
        - { name: sonata.admin, manager_type: orm, group: Test, label: Test Result }

   rithis.becrussia.admin.page:
      class: Rithis\BECRussiaBundle\Admin\PageAdmin
      arguments: [null, Rithis\BECRussiaBundle\Entity\Page, SonataAdminBundle:CRUD]
      tags:
        - { name: sonata.admin, manager_type: orm, group: Page, label: Page }

   rithis.becrussia.admin.library:
      class: Rithis\BECRussiaBundle\Admin\LibraryAdmin
      arguments: [null, Rithis\BECRussiaBundle\Entity\Library, SonataMediaBundle:MediaAdmin, @sonata.media.pool, @translator]
      tags:
        - { name: sonata.admin, manager_type: orm, group: Library, label: Library }
      calls:
        - [setTemplate, [list, RithisBECRussiaBundle:LibraryAdmin:list.html.twig]]
