services:
   rithis.becrussia.choice_list.reason:
      class: Rithis\BECRussiaBundle\Form\ChoiceList\ReasonChoiceList
      arguments: [@doctrine.orm.entity_manager]

   rithis.becrussia.choice_list.schedule:
      class: Rithis\BECRussiaBundle\Form\ChoiceList\ScheduleChoiceList
      arguments: [@doctrine.orm.entity_manager]

   rithis.becrussia.form.education_course_search:
      class: Rithis\BECRussiaBundle\Form\Type\EducationCourseSearchType
      arguments:
          - @rithis.becrussia.choice_list.reason
          - @rithis.becrussia.choice_list.schedule
