rithis_becrussia_index_get:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template: "RithisBECRussiaBundle:Index:get.html.twig"
    requirements:
        _method: GET

_rithis_becrussia:
    resource: "@RithisBECRussiaBundle/Controller"
    type: annotation

rithis_becrussia_page_get:
    pattern: /{uri}
    defaults: { _controller: RithisBECRussiaBundle:Page:get }
    requirements:
        _method: GET
        uri: .*
