services:
   rithis.becrussia.twig.page_extension:
       class: Rithis\BECRussiaBundle\Twig\PageExtension
       arguments: [@doctrine.orm.entity_manager]
       tags:
           - { name: twig.extension }
